title: Yashwanth's Vault
email: yashwanth1208@icloud.com

baseurl: "/yashwanths-vault"
url: "https://yashwanth1208.github.io"

remote_theme: knhash/jekyllBear

plugins:
  - jekyll-feed
  - jekyll-redirect-from
